# -*- coding: utf-8 -*-
"""tmdb_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_IOJ_IWyI9aeYI37jCl3WEnoltxzJuRQ
"""

import requests
import pandas as pd
import sqlite3
from google.colab import userdata

try:
    API_KEY = userdata.get('tmdb_api_key')
except Exception as e:
    print(f"Error: Could not find the secret. Check the name in the Key icon menu. Details: {e}")

url = f"https://api.themoviedb.org/3/discover/movie?api_key={API_KEY}"

response = requests.get(url)
data = response.json()

if 'results' in data and len(data['results']) > 0:
    movies_df = pd.DataFrame(data['results'])

    for col in movies_df.columns:
        if isinstance(movies_df[col].iloc[0], list):
            movies_df[col] = movies_df[col].astype(str)
    conn = sqlite3.connect('tmdb_data.db')
    movies_df.to_sql('movies', conn, if_exists='replace', index=False)
    conn.close()

    print("Success, Data cleaned and saved to tmdb_data.db.")
else:
    print("API Error:", data.get('status_message', 'No movies found. Check your API key.'))

import sqlite3
import pandas as pd

conn = sqlite3.connect('tmdb_data.db')
query = "SELECT * FROM movies"
df_loaded = pd.read_sql(query, conn)
conn.close()

print("Data successfully loaded from SQL")

print("\n1. Displaying the first 5 rows:")
display(df_loaded.head())

print("\n2. Summary Statistics (Numeric Columns):")
display(df_loaded.describe())

print("\n3. Count of Movies per Genre Combination:")
print(df_loaded['genre_ids'].value_counts())

print("\n4. Missing Values per Column:")
print(df_loaded.isnull().sum())